FROM node:20.11.1-alpine

WORKDIR /back

COPY package.json /back

RUN npm config set registry http://registry.npmjs.org/
RUN npm i -g next@latest
RUN npm install

#ENV
#ENV NODE

COPY . .

RUN npm run build

