name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect, pull and restart container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout main && git pull && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin-house-front:latest && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin-house-back:latest && docker compose up -d --no-deps --force-recreate --build back front && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
